### ISSUE TITLE
Scope change warning (actually an error) when fetching tokens

### ISSUE THREAD

**Issue by josephtate** [requests/requests-oauthlib#173]
My test script is pretty much straight from the http://requests-oauthlib.readthedocs.org/en/latest/examples/google.html Google OAuth2 tutorial.

```
#My test script
client_id =  '<snipped>.apps.googleusercontent.com'
client_secret = '<snipped>'
redirect_uri = '<snipped>'
token_url = "https://accounts.google.com/o/oauth2/token"
authz_url_base = 'https://accounts.google.com/o/oauth2/auth'
scope = ['https://www.googleapis.com/auth/plus.me', 'email']

from requests_oauthlib import OAuth2Session

google = OAuth2Session(client_id, scope=scope, redirect_uri=redirect_uri)

authorization_url, state = google.authorization_url(authz_url_base, access_type="online")

print 'Please go here and authorize,', authorization_url

redirect_response = raw_input('Paste the full redirect URL here:')

google.fetch_token(token_url, client_secret=client_secret, authorization_response=redirect_response)
```

And here's the output:

```
Please go here and authorize, https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=<snipped>
Paste the full redirect URL here:<snipped>
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    google.fetch_token(token_url, client_secret=client_secret, authorization_response=redirect_response)
  File "/home/jtate/.virtualenvs/crunch/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 199, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/jtate/.virtualenvs/crunch/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/jtate/.virtualenvs/crunch/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/home/jtate/.virtualenvs/crunch/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 406, in validate_token_parameters
    raise w
Warning: Scope has changed from "email https://www.googleapis.com/auth/plus.me" to "".
```

It looks like the Session object's scope isn't passed down into the oauthlib token parsing lib causing the error every time.

**Comment by josephtate** [comment]
This error is referenced in a comment in #157, but it's not related to that bug.

**Comment by josephtate** [comment]
I have a pull request against oauthlib to fix this: https://github.com/josephtate/oauthlib/pull/1

**Comment by josephtate** [comment]
Moved the pull request to https://github.com/idan/oauthlib/pull/323

**Comment by josephtate** [comment]
Closing since this is not a bug against requests-oauthlib
