### ISSUE TITLE
fetch_token fails if response contains url

### ISSUE THREAD

**Issue by zais** [requests/requests-oauthlib#176]
**Code**

``` python
        request_token_url = 'http://api.zenmoney.ru/oauth/request_token'
        oauth = OAuth1Session('aaaaaaaaaaaa', client_secret='bbbbb')  
        token = oauth.fetch_request_token(request_token_url)
```

**Debug**

```
    INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.zenmoney.ru
    DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth/request_token HTTP/1.1" 200 132
    DEBUG:requests_oauthlib.oauth1_session:Decoding token from response "login_url=http://api.zenmoney.ru/access/&oauth_token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaa&oauth_token_secret=bbbbbbbbbbbbb&oauth_callback_confirmed=true"
    Traceback (most recent call last):
      File "zenmoneycli.py", line 13, in <module>
        token = oauth.fetch_request_token(request_token_url)
      File "/home/user/Development/Python/zenmoneycli/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 261, in fetch_request_token
        token = self._fetch_token(url)
      File "/home/user/Development/Python/zenmoneycli/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 354, in _fetch_token
        raise ValueError(error)
    ValueError: Unable to decode token from token response. This is commonly caused by an unsuccessful request where a non urlencoded error message is returned. The decoding error was No JSON object could be decoded
```

As you can see response contains 'login_url=http://api.zenmoney.ru/access/' which is not 'safe' for urldecode.
Any workaround?

**Comment by singingwolfboy** [comment]
There has been no activity on this issue for over three years. As a result, I'm closing it. If this is still a problem for the latest version of requests-oauthlib, and you still need a fix for it, please open a new issue and reference this one.

**Comment by saprative** [comment]
I am facing this issue for a while. 

``    raise MissingCodeError("Missing code parameter in response.")
oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.

**Comment by singingwolfboy** [comment]
@saprative Which OAuth provider are you using?
