### ISSUE TITLE
Provide a way to specify the certificate's path for SSL verification

### ISSUE THREAD

**Issue by jacquesd** [requests/requests-oauthlib#181]
Hello, I am using the contrib client of `Flask-OAuthlib` which relies on `requests-oauthlib` and I have a SSL verification failure which appears to come from the `OAuth1Session` of `requests-oauthlib`:
```python
Traceback (most recent call last):
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jacques/Documents/code/indico-mobile/indicomobile/views/authentication.py", line 33, in login
    return indico.authorize(callback_uri)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask_oauthlib/contrib/client/application.py", line 181, in authorize
    response = oauth.fetch_request_token(self.request_token_url)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 261, in fetch_request_token
    token = self._fetch_token(url)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 340, in _fetch_token
    r = self.post(url)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```
It would be great if we could pass an argument to the session with the path of the certificate to be used when fetching the token (see [OAuth1Session#L340](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth1_session.py#L340))
I haven't tested OAuth2, but after a quick look at the `OAuth2Session` I think it might have the same issue on lines [176](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L176), [182](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L182) and [249](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L249).

If you are interested, I'll gladly work on a fix and submit a pull request.

**Comment by Lukasa** [comment]
You can. :smile: Set `session.verify` equal to the path of the certificate to use and that will automatically work.
