### ISSUE TITLE
Getting a ResponseNotReady() when reusing a request that requires a token

### ISSUE THREAD

**Issue by referentiallytransparent** [requests/requests-oauthlib#207]
Hello, 

I'm not too sure if i'm doing this right. I followed [this documentation](http://requests-oauthlib.readthedocs.org/en/latest/oauth2_workflow.html#legacy-application-flow) and this [example](http://requests-oauthlib.readthedocs.org/en/latest/examples/github.html) when setting up my work. 

I wanted to use the username-password flow to obtain an access token which translates to the `LegacyApplicationClient`

I managed to get everything set up properly and do a request to a bearer-token secured endpoint. However, I get a `requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())` when repeating the request using the OAuth2Session client. The first time, the request comes back with the correct response. 

I can use python-requests normally and repeat those requests once I have my token but I cannot seem to repeat requests on the OAuth2Session secured client. Any ideas what the issue may be?

Here is my example code:

```
import requests
from oauthlib.oauth2 import LegacyApplicationClient
from requests_oauthlib import OAuth2Session
from requests.auth import HTTPBasicAuth

# since we are using http instead of https
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

# Resource owner related
resource_owner_username = 'bob'
resource_owner_password = '1111'
resource_owner_endpoint = 'http://localhost:8080/myres'

client_app_id = 'client'
client_app_secret = 'supersecretpassword'

oauth_url = 'http://localhost:8081'
oauth_token_endpoint = '/oauth/token'
oauth_token_url = (oauth_url + oauth_token_endpoint)


offerOAuth = OAuth2Session(client=LegacyApplicationClient(client_id=client_app_id))

# Obtain a token with read all and write all privileges
# Manually refresh/(obtain for first time) token
token = offerOAuth.fetch_token(
    token_url=oauth_token_url,
    username=resource_owner_username,
    password=resource_owner_password,
    client_id=client_app_id,
    client_secret=client_app_secret,
    scope=['read.all', 'write.all'],
    verify=False,    # do not verify SSL certificate
)

print 'Token:', token['access_token']

# Request to resource owner endpoint through OAuth library
## Note: this cannot be repeated, gives me requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
for i in range(1,10):
    response = offerOAuth.get(resource_owner_endpoint, verify='False', timeout=10)
    print response.content


## Request to resource owner endpoint manually
## This can be repeated fine
for i in range(1,10):
    yetAnotherResponse = requests.get(
        url=resource_owner_endpoint,
        headers={'Authorization': ('Bearer ' + token['access_token'])}
    )
```

Here is my stack-trace
```
C:\Python27\python.exe C:/Users/Calvin/PycharmProjects/oauthcomms/oauthrequest.py
Token: tSllumb/OKYVytQa968GJ5ySJgBZpKY8F+tSkpUIqfUVl3vl5i0vklDhBfDP0P5E/nLpPFvyK+ub2cWQFS
{"page":{"previous":null,"next":null},"results":[]} -> Response from server is fine for the first time
Traceback (most recent call last):
  File "C:/Users/Calvin/PycharmProjects/oauthcomms/oauthrequest.py", line 47, in <module>
    response = offerOAuth.get(resource_owner_endpoint, verify='False', timeout=10)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests_oauthlib\oauth2_session.py", line 303, in request
    headers=headers, data=data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

**Comment by referentiallytransparent** [comment]
Perhaps I did not understand this correctly, after looking [here (more specifically, at the `profile` controller)](http://requests-oauthlib.readthedocs.org/en/latest/examples/real_world_example.html), it seems I should be doing `OAuth2Session(client=LegacyApplicationClient(client_id=client_app_id))` and passing my token obtained previously.

**Comment by referentiallytransparent** [comment]
This works. Thanks a lot and sorry for the confusion
```
# Obtain a token with read all and write all privileges
token = offerOAuth.fetch_token(
    token_url=oauth_token_url,
    username=resource_owner_username,
    password=resource_owner_password,
    client_id=client_app_id,
    client_secret=client_app_secret,
    scope=['read.all', 'write.all'],
    verify=False,    # do not verify SSL certificate
)

for i in range(1, 10):
    offerOAuth = OAuth2Session(client=LegacyApplicationClient(client_id=client_app_id), token=token)
    response = offerOAuth.get(resource_owner_endpoint, verify='False', timeout=10)
    print response.content
```
