### ISSUE TITLE
KeyError: 'oauth_token' after authorization

### ISSUE THREAD

**Issue by wjstevenson95** [requests/requests-oauthlib#288]
Keep getting the same KeyError when trying to access page data once the token is fetched. Not sure what is happening, here is the code:

````
client_id = os.environ['GITHUB_CLIENT_ID']
client_secret = os.environ['GITHUB_CLIENT_SECRET']
authorization_base_url = 'https://github.com/login/oauth/authorize'
token_url = 'https://github.com/login/oauth/access_token'
redirect_uri = 'https://polar-coast-87574.herokuapp.com/login/authorized'
@app.route('/login')
def login():
	github = OAuth2Session(client_id, redirect_uri=redirect_uri)
	(authorization_url,state) = github.authorization_url(authorization_base_url)
	session['oauth_state'] = state
	return redirect(authorization_url)


@app.route('/login/authorized', methods=["GET"])
def authorized():
	try:
		github = OAuth2Session(client_id, state=session['oauth_state'])
		token = github.fetch_token(token_url, client_secret=client_secret, authorization_response=request.url)
		session['oauth_token'] = token
		return redirect(url_for('.profile'))
	except KeyError as error:
		session.clear()
		print error
		return redirect(url_for('render_home'))


@app.route('/profile', methods=["GET"])
def profile():
	github = OAuth2Session(client_id, token=session['oauth_token'])
	return jsonify(github.get('https://api.github.com/user').json())
````
This is the logging information:

```
2017-09-08T06:20:55.566879+00:00 heroku[router]: at=info method=GET path="/profile" host=polar-coast-87574.herokuapp.com request_id=fac8fd6f-698a-4bd5-be88-d4c60c2ebe74 fwd="169.231.95.18" dyno=web.1 connect=0ms service=13ms status=500 bytes=456 protocol=http
2017-09-08T06:20:55.556176+00:00 app[web.1]: Exception on /profile [GET]
2017-09-08T06:20:55.556186+00:00 app[web.1]: Traceback (most recent call last):
2017-09-08T06:20:55.556188+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2017-09-08T06:20:55.556188+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-09-08T06:20:55.556189+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2017-09-08T06:20:55.556190+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-09-08T06:20:55.556191+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2017-09-08T06:20:55.556191+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-09-08T06:20:55.556192+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2017-09-08T06:20:55.556192+00:00 app[web.1]:     rv = self.dispatch_request()
2017-09-08T06:20:55.556193+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2017-09-08T06:20:55.556194+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-09-08T06:20:55.556195+00:00 app[web.1]:   File "/app/webapp.py", line 60, in profile
2017-09-08T06:20:55.556195+00:00 app[web.1]:     github = OAuth2Session(client_id, token=session['oauth_token'])
2017-09-08T06:20:55.556196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/local.py", line 368, in <lambda>
2017-09-08T06:20:55.556197+00:00 app[web.1]:     __getitem__ = lambda x, i: x._get_current_object()[i]
2017-09-08T06:20:55.556197+00:00 app[web.1]: KeyError: 'oauth_token'
```

Let me know if more information is needed!

EDIT: So clearing cookies for the heroku app seemed to get past the KeyErrors for oauth_state and oauth_token. Any way to get around this without having to clear cookies through chrome every time I want to login?

**Comment by Lukasa** [comment]
This is a problem in your code: you are trying to get the `oauth_token` out of the user session and are failing to. You should investigate why it's not present in the user session.

**Comment by joshlsullivan** [comment]
You can test your profile view with:

`if 'oauth_token' in session:
    github = OAuth2Session(client_id, token=session['oauth_token'])
    return jsonify(github.get('https://api.github.com/user').json())
else:
    return redirect(url_for('.login'))`

**Comment by wjstevenson95** [comment]
Thank you for your help! I managed to fix the issue a while back, but forgot to close the issue so I apologize for that. Turned out that I wasn't generating the app's secret_key correctly. Once I fixed that, everything else fell into place.
