### ISSUE TITLE
bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [requests/requests-oauthlib#321]
After
```
pip3 download requests-oauthlib --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)

Reason is that in this projects's `setup.py` line 50, argument `classifiers` should be an array, not a tuple. Replacing `(` by `[` fixes the issue.

See log below:
```
root@host:/build/requests-oauthlib-1.0.0.tar.gz.extracted/requests-oauthlib-1.0.0# python3 setup.py bdist_wheel upload -r artifactory
running bdist_wheel
running build
running build_py
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/requests_oauthlib
copying build/lib/requests_oauthlib/oauth1_session.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib
copying build/lib/requests_oauthlib/oauth2_auth.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib
creating build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/weibo.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/douban.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/mailchimp.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/fitbit.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/facebook.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/__init__.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/plentymarkets.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/slack.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/compliance_fixes/linkedin.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib/compliance_fixes
copying build/lib/requests_oauthlib/oauth2_session.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib
copying build/lib/requests_oauthlib/__init__.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib
copying build/lib/requests_oauthlib/oauth1_auth.py -> build/bdist.linux-ppc64le/wheel/requests_oauthlib
running install_egg_info
running egg_info
writing requests_oauthlib.egg-info/PKG-INFO
writing dependency_links to requests_oauthlib.egg-info/dependency_links.txt
writing requirements to requests_oauthlib.egg-info/requires.txt
writing top-level names to requests_oauthlib.egg-info/top_level.txt
reading manifest file 'requests_oauthlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.pyc'
writing manifest file 'requests_oauthlib.egg-info/SOURCES.txt'
Copying requests_oauthlib.egg-info to build/bdist.linux-ppc64le/wheel/requests_oauthlib-1.0.0-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/requests_oauthlib-1.0.0.dist-info/WHEEL
creating '/build/requests-oauthlib-1.0.0.tar.gz.extracted/requests-oauthlib-1.0.0/dist/requests_oauthlib-1.0.0-py2.py3-none-any.whl' and adding '.' to it
adding 'requests_oauthlib/__init__.py'
adding 'requests_oauthlib/oauth1_auth.py'
adding 'requests_oauthlib/oauth1_session.py'
adding 'requests_oauthlib/oauth2_auth.py'
adding 'requests_oauthlib/oauth2_session.py'
adding 'requests_oauthlib/compliance_fixes/__init__.py'
adding 'requests_oauthlib/compliance_fixes/douban.py'
adding 'requests_oauthlib/compliance_fixes/facebook.py'
adding 'requests_oauthlib/compliance_fixes/fitbit.py'
adding 'requests_oauthlib/compliance_fixes/linkedin.py'
adding 'requests_oauthlib/compliance_fixes/mailchimp.py'
adding 'requests_oauthlib/compliance_fixes/plentymarkets.py'
adding 'requests_oauthlib/compliance_fixes/slack.py'
adding 'requests_oauthlib/compliance_fixes/weibo.py'
adding 'requests_oauthlib-1.0.0.dist-info/LICENSE.txt'
adding 'requests_oauthlib-1.0.0.dist-info/top_level.txt'
adding 'requests_oauthlib-1.0.0.dist-info/WHEEL'
adding 'requests_oauthlib-1.0.0.dist-info/METADATA'
adding 'requests_oauthlib-1.0.0.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    test_suite='tests'
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by singingwolfboy** [comment]
According to [`git blame`](https://github.com/requests/requests-oauthlib/blame/master/setup.py#L50), the `classifiers` has been a tuple for about six years now. I'm surprised that no one else has pointed out this problem.

@thilo-maurer, can you send a pull request, please?

**Comment by sigmavirus24** [comment]
At least, the evidence of this being related to that is not self-evident.

**Comment by thilo-maurer** [comment]
@sigmavirus24  Yes, I opened this at multiple projects, ALL with the SAME issue: They pass in a tuple instead of an array. Seems everybody is using python2, where this seems to be no issue. (not looked into why that is)

**Comment by thilo-maurer** [comment]
For your convenience: Pull Request https://github.com/requests/requests-oauthlib/pull/322
