### ISSUE TITLE
please help requests

### ISSUE THREAD

**Issue by muhommadalmusawi** [requests/requests-oauthlib#342]
code:

import requests
import json
import chardet

email = ("fdff.aaaaaw2@mail.ru ")
payload ={'tk':email,'mk':'2762716611'
, 'button': 'submit'}

headers = {'user-agent': 'my-app/0.0.1'}
cookies = dict(cookies_are='working')
urlData = ('https://token-seshu.tk/')
webURL = requests.get(urlData, headers=headers,json=payload ,cookies=cookies,allow_redirects=True)
data = webURL
print(json.loads(data.content.decode('utf-8')))

================================================
please help

error

Traceback (most recent call last):
File "C:/Users/mayar/Desktop/ghf jf.py", line 14, in
print(json.loads(data.content.decode('utf-8')))
File "C:\Python34\lib\json_init_.py", line 318, in loads
return _default_decoder.decode(s)
File "C:\Python34\lib\json\decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by muhommadalmusawi** [comment]
code:

import requests
import json
import chardet

email = ("fdff.aaaaaw2@mail.ru ")
payload ={'tk':email,'mk':'2762716611'
, 'button': 'submit'}

headers = {'user-agent': 'my-app/0.0.1'}
cookies = dict(cookies_are='working')
urlData = ('https://token-seshu.tk/')
webURL = requests.get(urlData, headers=headers,json=payload ,cookies=cookies,allow_redirects=True)
data = webURL
print(json.loads(data.content.decode('utf-8')))

================================================
please help

error

Traceback (most recent call last):
File "C:/Users/mayar/Desktop/ghf jf.py", line 14, in
print(json.loads(data.content.decode('utf-8')))
File "C:\Python34\lib\json_init_.py", line 318, in loads
return _default_decoder.decode(s)
File "C:\Python34\lib\json\decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
